/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_startBlock = 1,
  anon_sym_LBRACE = 2,
  aux_sym_languageId_token1 = 3,
  anon_sym_RBRACE = 4,
  sym_source_file = 5,
  sym_definition = 6,
  sym__markdownBlock = 7,
  sym_languageId = 8,
  aux_sym_source_file_repeat1 = 9,
  aux_sym_languageId_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_startBlock] = "startBlock",
  [anon_sym_LBRACE] = "{",
  [aux_sym_languageId_token1] = "languageId_token1",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym__markdownBlock] = "_markdownBlock",
  [sym_languageId] = "languageId",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_languageId_repeat1] = "languageId_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_startBlock] = sym_startBlock,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_languageId_token1] = aux_sym_languageId_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym__markdownBlock] = sym__markdownBlock,
  [sym_languageId] = sym_languageId,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_languageId_repeat1] = aux_sym_languageId_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_startBlock] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_languageId_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__markdownBlock] = {
    .visible = false,
    .named = true,
  },
  [sym_languageId] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_languageId_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '`') ADVANCE(3);
      if (lookahead == '{') ADVANCE(6);
      if (lookahead == '}') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '}') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == '`') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == '`') ADVANCE(2);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_startBlock);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_languageId_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_languageId_token1);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(7);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_startBlock] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(10),
    [sym_definition] = STATE(2),
    [sym__markdownBlock] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_startBlock] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      sym_startBlock,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym__markdownBlock,
    STATE(3), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [14] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_startBlock,
    STATE(8), 1,
      sym__markdownBlock,
    STATE(3), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [28] = 3,
    ACTIONS(14), 1,
      aux_sym_languageId_token1,
    ACTIONS(16), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      aux_sym_languageId_repeat1,
  [38] = 3,
    ACTIONS(18), 1,
      aux_sym_languageId_token1,
    ACTIONS(20), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_languageId_repeat1,
  [48] = 3,
    ACTIONS(22), 1,
      aux_sym_languageId_token1,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_languageId_repeat1,
  [58] = 2,
    ACTIONS(27), 1,
      anon_sym_LBRACE,
    STATE(11), 1,
      sym_languageId,
  [65] = 1,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      sym_startBlock,
  [70] = 1,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_startBlock,
  [75] = 1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
  [79] = 1,
    ACTIONS(35), 1,
      sym_startBlock,
  [83] = 1,
    ACTIONS(37), 1,
      sym_startBlock,
  [87] = 1,
    ACTIONS(39), 1,
      sym_startBlock,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 28,
  [SMALL_STATE(5)] = 38,
  [SMALL_STATE(6)] = 48,
  [SMALL_STATE(7)] = 58,
  [SMALL_STATE(8)] = 65,
  [SMALL_STATE(9)] = 70,
  [SMALL_STATE(10)] = 75,
  [SMALL_STATE(11)] = 79,
  [SMALL_STATE(12)] = 83,
  [SMALL_STATE(13)] = 87,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [14] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [16] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [18] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [20] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_languageId_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_languageId_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__markdownBlock, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_languageId, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_languageId, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_quarto(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "quarto",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
